version: '3.8'
services:
  cambio-db:
    image: mysql:latest
    container_name: cambio-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Cuiaba
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - '3311:3306'
    expose:
      - 3311
    stdin_open: true
    tty: true
    volumes:
      - .docker/cambio_db:/var/lib/mysql
      - .docker/init_cambio_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    networks:
      - microservice-network
  book-db:
    image: mysql:latest
    container_name: book-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Cuiaba
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - '3310:3306'
    expose:
      - 3310
    stdin_open: true
    tty: true
    volumes:
      - .docker/book_db:/var/lib/mysql
      - .docker/init_book_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    networks:
      - microservice-network
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin
    ports:
      - '9411:9411'
    networks:
      - microservice-network
  naming-server:
    image: da0hn/naming-server:1.0.0
    container_name: naming-server
    environment:
      - PORT=8761
    ports:
      - '8761:8761'
    networks:
      - microservice-network
  api-gateway:
    image: da0hn/api-gateway:1.0.0
    container_name: api-gateway
    environment:
      - PORT=8765
      - ZIPKIN_URL=zipkin-server
      - ZIPKIN_PORT=9411
      - EUREKA_URL=naming-server
      - EUREKA_PORT=8761
    ports:
      - '8765:8765'
    depends_on:
      - naming-server
      - zipkin-server
    networks:
      - microservice-network
  book-service:
    image: da0hn/book-service:latest
    container_name: book-service
    build:
      context: ./book-service
    restart: on-failure
    ports:
      - '8100:8100'
    environment:
#      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
#      SPRING_RABBITMQ_HOST: rabbit-mq
#      SPRING_ZIPKIN_SENDER_TYPE: rabbit
        - TZ=America/Cuiaba
        - DATABASE_URL=book-db
        - DATABASE_PORT=3306
        - DATABASE=book_db
        - DATABASE_USER=root
        - DATABASE_PASSWORD=admin123
        - PORT=8100
        - ZIPKIN_URL=zipkin-server
        - ZIPKIN_PORT=9411
        - EUREKA_URL=naming-server
        - EUREKA_PORT=8761
    depends_on:
      - naming-server
      - book-db
    networks:
      - microservice-network
  cambio-service:
    image: da0hn/cambio-service:latest
    container_name: cambio-service
    build:
      context: ./cambio-service
    restart: on-failure
    ports:
      - '8000:8000'
    environment:
      #      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      #      SPRING_RABBITMQ_HOST: rabbit-mq
      #      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      - TZ=America/Cuiaba
      - DATABASE_URL=cambio-db
      - DATABASE_PORT=3306
      - DATABASE=cambio_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin123
      - PORT=8000
      - ZIPKIN_URL=zipkin-server
      - ZIPKIN_PORT=9411
      - EUREKA_URL=naming-server
      - EUREKA_PORT=8761
    depends_on:
      - naming-server
      - cambio-db
    networks:
      - microservice-network
networks:
  microservice-network:
    driver: bridge
    name: microservice-network
