version: '3.8'
services:
  cambio-db:
    image: mysql:latest
    container_name: cambio-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cambio_db
      MYSQL_USER: cambio_db
      MYSQL_PASSWORD: cambio_db
    volumes:
      - .docker/init_cambio_db.sql:/docker-entrypoint-initdb.d/init.sql
      - .docker/cambio_db:/var/lib/mysql
    restart: on-failure
    networks:
      - microservice-network
  book-db:
    image: mysql:latest
    container_name: book-db
#    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3307'
    environment:
#      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: book_db
#      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3307
      MYSQL_DATABASE: book_db
      MYSQL_USER: book_db
      MYSQL_PASSWORD: book_db
#    expose:
#      - 3307
    volumes:
      - .docker/book_db:/var/lib/mysql
      - .docker/init_book_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    networks:
      - microservice-network
  zipkin:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin
    ports:
      - '9411:9411'
    networks:
      - microservice-network
  naming-server:
    image: da0hn/naming-server:1.0.0
    container_name: naming-server
    environment:
      - PORT=8761
    ports:
      - '8761:8761'
    networks:
      - microservice-network
  api-gateway:
    image: da0hn/api-gateway:1.0.0
    container_name: api-gateway
    environment:
      - PORT=8765
      - ZIPKIN_URL=zipkin
      - ZIPKIN_PORT=9411
      - EUREKA_URL=naming-server
      - EUREKA_PORT=8761
    ports:
      - '8765:8765'
    depends_on:
      - naming-server
      - zipkin
    networks:
      - microservice-network
  book-service:
    image: da0hn/book-service:1.0.7
    container_name: book-service
    build:
      context: ./book-service
    ports:
      - '8100:8100'
    environment:
      - DATABASE_URL=book-db
      - DATABASE_PORT=3307
      - DATABASE=book_db
      - DATABASE_USER=book_db
      - DATABASE_PASSWORD=book_db
      - PORT=8100
      - ZIPKIN_URL=zipkin
      - ZIPKIN_PORT=9411
      - EUREKA_URL=naming-server
      - EUREKA_PORT=8761
      - CAMBIO_URL=cambio-service
      - CAMBIO_PORT=8000
    depends_on:
      - naming-server
      - api-gateway
      - book-db
    networks:
      - microservice-network
networks:
  microservice-network:
    driver: bridge
    name: microservice-network
