version: '3.8'
services:
  cambio-db:
    image: mysql:latest
    container_name: cambio-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cambio_db
      MYSQL_USER: cambio_db
      MYSQL_PASSWORD: cambio_db
    volumes:
      - .docker/init_cambio_db.sql:/docker-entrypoint-initdb.d/init.sql
      - .docker/cambio_db:/var/lib/mysql
    restart: on-failure
    networks:
      - microservice-network
  book-db:
    image: mysql:latest
    container_name: book-db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db
      MYSQL_USER: book_db
      MYSQL_PASSWORD: book_db
    volumes:
      - .docker/book_db:/var/lib/mysql
      - .docker/init_book_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    networks:
      - microservice-network
  naming-server:
    image: da0hn/naming-server:1.0.0
    container_name: naming-server
    environment:
      - PORT=8761
    ports:
      - '8761:8761'
    networks:
      - microservice-network
networks:
  microservice-network:
    driver: bridge
    name: microservice-network
