cambio-service:
  url: http://${CAMBIO_URL:localhost}:${CAMBIO_PORT:8000}
server:
  port: ${PORT:8100}
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DATABASE_PORT:3310}/${DATABASE:book_db}?autoReconnect=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:admin123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DATABASE_PORT:3310}/${DATABASE:book_db}?autoReconnect=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:admin123}
  sleuth:
    sampler:
      probability: 1.0 # Trace 100% of logs
  zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:${ZIPKIN_PORT:9411}/
    sender:
      type: ${ZIPKIN_SENDER_TYPE:rabbit}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    password: ${RABBITMQ_PASSWORD:guest}
    username: ${RABBITMQ_USER:guest}
    port: ${RABBITMQ_PORT:5672}
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost}:${EUREKA_PORT:8761}/eureka
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
logging:
  level:
    org:
      flywaydb=debug:
