server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/da0hn/spring-cloud-greeting-config-server
          default-label: master
          search-paths:
            - 'greeting-service*'
