name: Continuos Integration with Github


on: [ push ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java SDK 17
        uses: actions/setup-java@v3.4.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Eureka Naming Server Container Image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests

